FROM debian:buster

RUN apt-get update && apt-get install -y python python-dev python-setuptools gcc libtinfo-dev zlib1g-dev \
    git wget cmake build-essential unzip libedit-dev

WORKDIR /usr
RUN wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-aarch64-linux-gnu.tar.xz
RUN tar -xvf clang+llvm-6.0.0-aarch64-linux-gnu.tar.xz --strip 1 && rm clang+llvm-6.0.0-aarch64-linux-gnu.tar.xz

WORKDIR /build
RUN git clone --recursive https://github.com/dmlc/tvm && cd tvm && \
    git submodule init && git submodule update
RUN cd tvm && mkdir build && cd build && cmake -DUSE_LLVM=ON ../ && \
    make -j4
RUN cd tvm/nnvm && make -j4
RUN cd tvm/python &&  python setup.py install --user && cd ../ && \
    cd topi/python && python setup.py install --user && cd ../../ && \
    cd nnvm/python && python setup.py install --user
RUN apt-get install -y python-pip
RUN pip install mxnet
RUN apt-get install -y python-imaging
RUN pip install Pillow
ADD from_mxnet.py /root/from_mxnet.py
RUN python /root/from_mxnet.py
