FROM arm32v7/debian:stretch
RUN apt-get update && apt-get install -y git scons cmake wget unzip curl build-essential vim \
    libprotobuf-dev protobuf-compiler libopencv-dev
WORKDIR /root
RUN git clone https://github.com/deepinsight/mtcnn-ncnn mtcnn && \
    cd mtcnn && \
    mkdir build && cd build && \
    cmake ../ && make -j6
RUN cd /root && git clone https://github.com/Tencent/ncnn && \
    cd ncnn && mkdir build && cd build && \
    cmake ../ && make -j6
