FROM arm64v8/debian:stretch
RUN apt-get update && apt-get install -y git scons cmake wget unzip curl build-essential
WORKDIR /root

ENV CL_DIR /root/ComputeLibrary

RUN git clone https://github.com/ARM-software/ComputeLibrary && \
    cd /root/ComputeLibrary && \
    scons -j 6 arch=arm64-v8a neon=0 opencl=1 openvx=0 Werror=0 debug=0 validation_tests=0 benchmark_tests=1 debug=0 Werror=0 asserts=1 examples=1 standalone=0 cppthreads=1 openmp=1 

ADD Mali/libmali-midgard-4th-r13p0.so /usr/lib/libmali.so
RUN apt-get update && apt-get install -y libdrm2 libx11-xcb1 libxcb-dri2-0 && \
    ln -s /usr/lib/libmali.so /usr/lib/libOpenCL.so && \
    ln -s /usr/lib/libmali.so /usr/lib/libGLES_mali.so

WORKDIR ${CL_DIR}/build
RUN LD_LIBRARY_PATH=`pwd` ./tests/arm_compute_benchmark
