FROM lambdazhang/raidcdn:tf_1.8

ADD export/wheels /root/wheels
ADD Mali/libmali-midgard-4th-r13p0.so /usr/lib/libmali.so
ADD ./test_runtime.py /root/test_runtime.py

RUN apt-get update && apt-get install -y --no-install-recommends libopenblas-base git \
    python-setuptools python-pip libgfortran3 \
    python-numpy python-scipy wget \
    python-matplotlib python-h5py python-requests python-psutil \
    unzip python-sklearn curl python-pil \
    python-opencv && \
    wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-aarch64-linux-gnu.tar.xz && \
    tar -xvf clang+llvm-6.0.0-aarch64-linux-gnu.tar.xz --strip 1 && rm clang+llvm-6.0.0-aarch64-linux-gnu.tar.xz && \
    cd /root/wheels && pip install *.whl && rm -rf /root/wheels && \
    ln -s /usr/lib/libmali.so /usr/lib/libOpenCL.so && \
    ln -s /usr/lib/libmali.so /usr/lib/libGLES_mali.so && \
    cd /root && \
    python /root/test_runtime.py && \
    apt-get remove -y zlib1g-dev libjpeg-dev libtiff5-dev python-dev build-essential && \
    apt-get autoremove -y && \
    rm -rf /root/.cache/pip/ && rm /tensorflow-1.8.0-cp27-none-linux_aarch64.whl && rm /test.py && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
